import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.geom.Rectangle2D;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.SystemColor;
import javax.swing.SwingConstants;
import java.awt.Component;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ni3
 */


 
class TreeComponent extends JComponent {
    
   public synchronized void setValues(GraphicalTree gt,char f,String v) {
      this.tree = gt;
      flag = f;
      val = v;
      repaint();
   }
   
   
   public synchronized void paintComponent(Graphics g) {
      int f = 0,gap = 0;
      switch(flag)
      {
          case 'i':
        	  tree.insert(val,g);
              gap = tree.depth(tree.root);
              gap = gap * gap * 10;
              tree.draw(tree.root, g ,getWidth() / 2, 50,getWidth() / 2, 50,0,gap);
              f = 1;
              break;      
           case 'd':
              if(tree.delete(val,g) == 1) {
            	  gap = tree.depth(tree.root);
                  gap = gap * gap * 10;
                  tree.draw(tree.root, g ,getWidth() / 2, 50,getWidth() / 2, 50,0,gap);
              }
                  f = 1;
                  break;
           case 'f':
        	   if(tree.find(val,g) == 1) {
        		   gap = tree.depth(tree.root);
                   gap = gap * gap * 10;
                   tree.draw(tree.root, g ,getWidth() / 2, 50,getWidth() / 2, 50,0,gap);
                        //JOptionPane.showMessageDialog(null, val+" Found..!", "alert", JOptionPane.ERROR_MESSAGE); 
        	   }
        	   else
                    {
                          // JOptionPane.showMessageDialog(null, val+" not found..!", "alert", JOptionPane.ERROR_MESSAGE); 
                    }
                    f = 1;
               
       }
       if(tree != null)
       {
            gap = tree.depth(tree.root);
            gap = gap * gap * 10;
             tree.draw(tree.root, g ,getWidth() / 2, 50,getWidth() / 2, 50,0, gap) ;
       }
       flag = 'k';
   
      
   }
   String val;
    char flag;
   GraphicalTree tree;
}



 
public class TreePanel extends javax.swing.JPanel {

    /**
     * Creates new form TreePanel
     */
    TreeComponent comp;
    GraphicalTree gt;
    public TreePanel() {
        initComponents();
        comp = new TreeComponent();
        bstPanel.add(comp,BorderLayout.CENTER);
        gt = new GraphicalTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeCenterPanel = new javax.swing.JPanel();
        treePane = new javax.swing.JTabbedPane();
        bstPanel = new javax.swing.JPanel();
        bstNorthPanel = new javax.swing.JPanel();
        bstInsertButton = new javax.swing.JButton();
        bstInsertButton.setIcon(new ImageIcon(TreePanel.class.getResource("/image/insert.png")));
        bstDelButton = new javax.swing.JButton();
        bstDelButton.setIcon(new ImageIcon(TreePanel.class.getResource("/image/delete.png")));
        bstFindButton = new javax.swing.JButton();
        bstFindButton.setIcon(new ImageIcon(TreePanel.class.getResource("/image/find.png")));
        bstInsertText = new javax.swing.JTextField();
        bstDelText = new javax.swing.JTextField();
        bstFindText = new javax.swing.JTextField();
        bstSouthPanel = new javax.swing.JPanel();
        bstSlider = new javax.swing.JSlider();
        bstRunButton = new javax.swing.JButton();
        bstRunButton.setBackground(SystemColor.inactiveCaptionBorder);
        bstRunButton.setIcon(new ImageIcon(TreePanel.class.getResource("/image/run.png")));
        bstStepButton = new javax.swing.JButton();
        bstStepButton.setBackground(Color.WHITE);
        bstStepButton.setIcon(new ImageIcon(TreePanel.class.getResource("/image/step.png")));
        jSeparator3 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        treeCenterPanel.setLayout(new javax.swing.BoxLayout(treeCenterPanel, javax.swing.BoxLayout.LINE_AXIS));

        bstPanel.setBackground(new java.awt.Color(254, 254, 254));
        bstPanel.setLayout(new java.awt.BorderLayout());

        bstInsertButton.setText("Insert");
        bstInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstInsertButtonActionPerformed(evt);
            }
        });

        bstDelButton.setText("Delete");
        bstDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstDelButtonActionPerformed(evt);
            }
        });

        bstFindButton.setText("Find");
        bstFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstFindButtonActionPerformed(evt);
            }
        });

        bstInsertText.setColumns(10);
        bstInsertText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstInsertTextActionPerformed(evt);
            }
        });
        bstInsertText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bstInsertTextKeyPressed(evt);
            }
        });

        bstDelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstDelTextActionPerformed(evt);
            }
        });

        bstFindText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstFindTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bstNorthPanelLayout = new javax.swing.GroupLayout(bstNorthPanel);
        bstNorthPanelLayout.setHorizontalGroup(
        	bstNorthPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(bstNorthPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(bstInsertText, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(bstInsertButton, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(bstDelText, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(bstDelButton)
        			.addGap(22)
        			.addComponent(bstFindText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(bstFindButton)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bstNorthPanelLayout.setVerticalGroup(
        	bstNorthPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(bstNorthPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(bstNorthPanelLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bstInsertButton)
        				.addComponent(bstDelButton)
        				.addComponent(bstFindButton)
        				.addComponent(bstInsertText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bstDelText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bstFindText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        bstNorthPanelLayout.linkSize(SwingConstants.HORIZONTAL, new Component[] {bstInsertText, bstDelText, bstFindText});
        bstNorthPanel.setLayout(bstNorthPanelLayout);

        bstPanel.add(bstNorthPanel, java.awt.BorderLayout.PAGE_START);

        bstSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Animation Speed", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bitstream Charter", 0, 12), new java.awt.Color(222, 29, 29))); // NOI18N

        bstRunButton.setText("Run");
        bstRunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstRunButtonActionPerformed(evt);
            }
        });

        bstStepButton.setText("Step");

        javax.swing.GroupLayout bstSouthPanelLayout = new javax.swing.GroupLayout(bstSouthPanel);
        bstSouthPanelLayout.setHorizontalGroup(
        	bstSouthPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(bstSouthPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(bstRunButton)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(bstStepButton)
        			.addGap(287)
        			.addComponent(bstSlider, GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        			.addContainerGap())
        		.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        bstSouthPanelLayout.setVerticalGroup(
        	bstSouthPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(bstSouthPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(bstSouthPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(bstSouthPanelLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(bstRunButton)
        					.addComponent(bstStepButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        				.addComponent(bstSlider, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        			.addGap(15))
        );
        bstSouthPanel.setLayout(bstSouthPanelLayout);

        bstPanel.add(bstSouthPanel, java.awt.BorderLayout.SOUTH);

        treePane.addTab("Binary Search Tree", bstPanel);

        treeCenterPanel.add(treePane);

        add(treeCenterPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bstInsertTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstInsertTextActionPerformed
        
    }//GEN-LAST:event_bstInsertTextActionPerformed

    private void bstDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstDelButtonActionPerformed
        bstInsertButton.setEnabled(false);
        bstDelButton.setEnabled(false);
        bstFindButton.setEnabled(false);
        
        comp.setValues(gt,'d',bstDelText.getText());
        bstDelText.setText("");
        
        bstInsertButton.setEnabled(true);
        bstDelButton.setEnabled(true);
        bstFindButton.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bstDelButtonActionPerformed

    private void bstDelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstDelTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bstDelTextActionPerformed

    private void bstFindTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstFindTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bstFindTextActionPerformed

    private void bstRunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstRunButtonActionPerformed
        
    }//GEN-LAST:event_bstRunButtonActionPerformed

    private void bstInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstInsertButtonActionPerformed
        bstInsertButton.setEnabled(false);
        bstDelButton.setEnabled(false);
        bstFindButton.setEnabled(false);
        
        comp.setValues(gt,'i',bstInsertText.getText());
        bstInsertText.setText("");
        
        bstInsertButton.setEnabled(true);
        bstDelButton.setEnabled(true);
        bstFindButton.setEnabled(true);
        
    }//GEN-LAST:event_bstInsertButtonActionPerformed

    private void bstFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstFindButtonActionPerformed
        bstInsertButton.setEnabled(false);
        bstDelButton.setEnabled(false);
        bstFindButton.setEnabled(false);
        
        comp.setValues(gt,'f',bstFindText.getText());
        bstFindText.setText("");
        
        bstInsertButton.setEnabled(true);
        bstDelButton.setEnabled(true);
        bstFindButton.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bstFindButtonActionPerformed

    private void bstInsertTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bstInsertTextKeyPressed
        // TODO add your handling code here:
       if (evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
        bstInsertButton.setEnabled(false);
        bstDelButton.setEnabled(false);
        bstFindButton.setEnabled(false);
        
        comp.setValues(gt,'i',bstInsertText.getText());
        bstInsertText.setText("");
        
        bstInsertButton.setEnabled(true);
        bstDelButton.setEnabled(true);
        bstFindButton.setEnabled(true);
       }

    }//GEN-LAST:event_bstInsertTextKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bstDelButton;
    private javax.swing.JTextField bstDelText;
    private javax.swing.JButton bstFindButton;
    private javax.swing.JTextField bstFindText;
    private javax.swing.JButton bstInsertButton;
    private javax.swing.JTextField bstInsertText;
    private javax.swing.JPanel bstNorthPanel;
    private javax.swing.JPanel bstPanel;
    private javax.swing.JButton bstRunButton;
    private javax.swing.JSlider bstSlider;
    private javax.swing.JPanel bstSouthPanel;
    private javax.swing.JButton bstStepButton;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel treeCenterPanel;
    private javax.swing.JTabbedPane treePane;
    // End of variables declaration//GEN-END:variables
}